const fs = require('fs');
let code = fs.readFileSync('firestore.rules', 'utf8');

const newRules = `
      // ==========================================
      // PHASE 2: SUBSCRIPTION & ENTITLEMENT SYSTEM
      // ==========================================
      match /subscriptions/{subscriptionId} {
        allow read: if isSuperAdmin() || sameCompany(companyId);
        allow write: if isSuperAdmin(); // Only Super Admin or Webhook backend can update subscriptions
      }
      match /entitlements/{moduleId} {
        allow read: if isSuperAdmin() || sameCompany(companyId);
        allow write: if isSuperAdmin(); // Only Super Admin or Webhook backend can update entitlements
      }
      match /payments/{paymentId} {
        allow read: if isSuperAdmin() || isCompanyAdmin(companyId);
        allow write: if false; // Payments are created by secure backend webhook only
      }
      match /invoices/{invoiceId} {
        allow read: if isSuperAdmin() || isCompanyAdmin(companyId);
        allow write: if false; // Invoices generated by backend
      }
      match /subscriptionHistory/{historyId} {
        allow read: if isSuperAdmin() || isCompanyAdmin(companyId);
        allow write: if false; // Immutable history written by backend
      }
`;

// Insert the new rules right after `allow delete: if isSuperAdmin();` inside `match /companies/{companyId} {`
code = code.replace(
  /allow delete: if isSuperAdmin\(\);\n/,
  `allow delete: if isSuperAdmin();\n${newRules}\n`
);

// Add global rules for plans and modules
const globalRules = `
    match /plans/{planId} {
      allow read: if signedIn();
      allow write: if isSuperAdmin();
    }
    match /modules/{moduleId} {
      allow read: if signedIn();
      allow write: if isSuperAdmin();
    }
`;

code = code.replace(
  /match \/company_codes\/\{codeId\}/,
  `${globalRules}\n    match /company_codes/{codeId}`
);

fs.writeFileSync('firestore.rules', code);
